#include "JobFile/JobFile.hpp"

#include <string>
#include <map>
#include <iostream>

#include "JobFile/ParameterExtractor/PrusaSlicer.hpp"
#include "Main.hpp"

namespace Prosur::JobFile{

	enum Type{
		PrusaSlicer
	};

	map<string, Type> signatures = {
			{"generated by PrusaSlicer", PrusaSlicer}
	};

	static Type identify(string& fileData){
		for(const auto& [signature, type]: signatures){
			if(fileData.find(signature) != string::npos){
				return type;
			}
		}
		log("JobFile: Unable to identify job file for job parameter extraction.");
		terminate();
	}

	map<string, string> extractParameters(string& fileData){
		switch(identify(fileData)){
		case PrusaSlicer:
			return Extractor::PrusaSlicer::extractParameters(fileData);
		}
		return {};
	}

}
